### ISSUE TITLE
Add offset on simulation

### ISSUE THREAD

**Issue by MAFoujols** [PBrockmann/interMonitoring#7]
Is it possible to add the possibility to translate the beginning of one simulation/line. It is possible 1)  to use the date of the simulation or 2)  an index ie all simulations started from the same starting point. A 3) possibility with a translated index for specified lines could be useful.
For example : 
one historical simulation (1850-2010) has been started from an Control run at a specific date : 2120 for example. We want to use indexes (2) and to translate the beginning of the historical simulation (1850) near the date (2120) of the Control simulation.
Thanks for examining this issue.

**Comment by PBrockmann** [comment]
Could you point me a interMonitoring output to test this offset feature ?

**Comment by MAFoujols** [comment]
The original intermonitoring has been deleted : " le historical fait à peu près ce qu'on attend de lui (réchauffement de 1°C sur 1850-2012, voire un peu moins si on prend en compte le fait que le piControl n'était pas complètement stabilisé, un peu rapide sur la fin, mais on sait que la variabilité naturelle a joué contre le réchauffement dans le vrai monde). Et le piControl suivi du historical nous amènent près du pdControl (c'est le test demandé par Frédéric pour valider le pmagic). C'est ici grâce à Sébastien : 
http://webservices.ipsl.jussieu.fr/monitoring_fromprodiguer/tmp/fegg_plot01_lSEppA_prod/

Attention, le historical a été branché en l'an 2120 du piControl, **il faut donc mentalement translater la courbe bleue (et la rouge quand elle existe) vers la droite**. Le pdControl montre sur la fin un refroidissement de 0.4°C suivi d'un réchauffement d'autant assez spectaculaires... (on voit ça aussi sur le diag NADW). "

I tried to redo this one. pdControl+piControl+historical with IPSLCM607.  We want to superpose blue points. With indices it's like a translation of xx indices. With dates, actually dates have no signification for both pxControl and both could be translated to different 'virtual' dates to superpose blue points.

**Comment by MAFoujols** [comment]
One picture to explain the issue :
[intermon_dates_indices.pdf](https://github.com/PBrockmann/interMonitoring/files/957987/intermon_dates_indices.pdf)

Full intermonitoring : 
(indices) http://webservices.ipsl.jussieu.fr/monitoring_fromprodiguer/tmp/fegg_plot02_8Ecs57_prod/

(dates) http://webservices.ipsl.jussieu.fr/monitoring_fromprodiguer/tmp/fegg_plot01_QQLdwA_prod/

**Comment by PBrockmann** [comment]
Not sure to fully understand what is asked. Please be more focused on the technical request and if possible write in english. What I understand is that one needs to apply offset on the different variables displayed.

Attached 2 scripts and their corresponding images as a first try.
Offset can be made on the time axis so this will be possible only when dates representation is requested (not indices).

```pyferret
yes? go interMonitoring_plot01_classic
```

[interMonitoring_plot01_classic.txt](https://github.com/PBrockmann/interMonitoring/files/961745/interMonitoring_plot01_classic.txt)
![classic](https://cloud.githubusercontent.com/assets/5402758/25485917/da4b73a2-2b5f-11e7-98de-047deb022022.png)

```pyferret
yes? go interMonitoring_plot01_offset "" "" `2120-1850`
```
Optionnal arguments are:
- argument 1 is the monitoring files (default=ATM_t2m_global_ave.nc)
- argument 2 is the smooth value (default=12)
- argument 3 is the offset for var1 (default=0)
- argument 4 is the offset for var2 (default=0)
- argument 5 is the offset for var3 (default=0)

[interMonitoring_plot01_offset.txt](https://github.com/PBrockmann/interMonitoring/files/961746/interMonitoring_plot01_offset.txt)
![offset](https://cloud.githubusercontent.com/assets/5402758/25485918/da4ca61e-2b5f-11e7-9a7c-2b8ced63fce0.png)

Now I need to think to renew the interface and allow user to precise this offset value for each input files.
Waiting that you can run this jnl with the bash loop script prepared by the interMonitoring (http://webservices2017.ipsl.fr/interMonitoring/).

**Comment by PBrockmann** [comment]
Simpler solution by redefining T0 (zero time).

```
yes? go interMonitoring_plot01_offset2.jnl "" "" 2200
```
Optionnal arguments are:
- argument 1 is the monitoring files (default=ATM_t2m_global_ave.nc)
- argument 2 is the smooth value (default=12)
- argument 3 is the T0 year for var1 (default=no change)
- argument 4 is the T0 year for var2 (default=no change)
- argument 5 is the T0 year for var3 (default=no change)

[interMonitoring_plot01_offset2.txt](https://github.com/PBrockmann/interMonitoring/files/961983/interMonitoring_plot01_offset2.txt)

**Comment by PBrockmann** [comment]
Implement the 1st solution (dynamic change of time axis as in interMonitoring_plot01_offset.txt) in a Release Candidate available from:
http://webservices2017.ipsl.fr/interMonitoring_RC1/

2017/05/11: Pass RC1 to production from http://webservices2017.ipsl.fr/interMonitoring
